# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ClassModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _class: str=None):  # noqa: E501
        """ClassModel - a model defined in Swagger

        :param _class: The _class of this ClassModel.  # noqa: E501
        :type _class: str
        """
        self.swagger_types = {
            '_class': str
        }

        self.attribute_map = {
            '_class': '_class'
        }
        self.__class = _class

    @classmethod
    def from_dict(cls, dikt) -> 'ClassModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClassModel of this ClassModel.  # noqa: E501
        :rtype: ClassModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _class(self) -> str:
        """Gets the _class of this ClassModel.


        :return: The _class of this ClassModel.
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class: str):
        """Sets the _class of this ClassModel.


        :param _class: The _class of this ClassModel.
        :type _class: str
        """

        self.__class = _class
