# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Client(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, client: str=None):  # noqa: E501
        """Client - a model defined in Swagger

        :param client: The client of this Client.  # noqa: E501
        :type client: str
        """
        self.swagger_types = {
            'client': str
        }

        self.attribute_map = {
            'client': 'client'
        }
        self._client = client

    @classmethod
    def from_dict(cls, dikt) -> 'Client':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Client of this Client.  # noqa: E501
        :rtype: Client
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client(self) -> str:
        """Gets the client of this Client.


        :return: The client of this Client.
        :rtype: str
        """
        return self._client

    @client.setter
    def client(self, client: str):
        """Sets the client of this Client.


        :param client: The client of this Client.
        :type client: str
        """

        self._client = client
