# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MapTest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, map_map_of_string: Dict[str, Dict[str, str]]=None, map_of_enum_string: Dict[str, str]=None):  # noqa: E501
        """MapTest - a model defined in Swagger

        :param map_map_of_string: The map_map_of_string of this MapTest.  # noqa: E501
        :type map_map_of_string: Dict[str, Dict[str, str]]
        :param map_of_enum_string: The map_of_enum_string of this MapTest.  # noqa: E501
        :type map_of_enum_string: Dict[str, str]
        """
        self.swagger_types = {
            'map_map_of_string': Dict[str, Dict[str, str]],
            'map_of_enum_string': Dict[str, str]
        }

        self.attribute_map = {
            'map_map_of_string': 'map_map_of_string',
            'map_of_enum_string': 'map_of_enum_string'
        }
        self._map_map_of_string = map_map_of_string
        self._map_of_enum_string = map_of_enum_string

    @classmethod
    def from_dict(cls, dikt) -> 'MapTest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MapTest of this MapTest.  # noqa: E501
        :rtype: MapTest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def map_map_of_string(self) -> Dict[str, Dict[str, str]]:
        """Gets the map_map_of_string of this MapTest.


        :return: The map_map_of_string of this MapTest.
        :rtype: Dict[str, Dict[str, str]]
        """
        return self._map_map_of_string

    @map_map_of_string.setter
    def map_map_of_string(self, map_map_of_string: Dict[str, Dict[str, str]]):
        """Sets the map_map_of_string of this MapTest.


        :param map_map_of_string: The map_map_of_string of this MapTest.
        :type map_map_of_string: Dict[str, Dict[str, str]]
        """

        self._map_map_of_string = map_map_of_string

    @property
    def map_of_enum_string(self) -> Dict[str, str]:
        """Gets the map_of_enum_string of this MapTest.


        :return: The map_of_enum_string of this MapTest.
        :rtype: Dict[str, str]
        """
        return self._map_of_enum_string

    @map_of_enum_string.setter
    def map_of_enum_string(self, map_of_enum_string: Dict[str, str]):
        """Sets the map_of_enum_string of this MapTest.


        :param map_of_enum_string: The map_of_enum_string of this MapTest.
        :type map_of_enum_string: Dict[str, str]
        """
        allowed_values = ["UPPER", "lower"]  # noqa: E501
        if not set(map_of_enum_string.keys()).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid keys in `map_of_enum_string` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(map_of_enum_string.keys()) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._map_of_enum_string = map_of_enum_string
