# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NumberOnly(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, just_number: float=None):  # noqa: E501
        """NumberOnly - a model defined in Swagger

        :param just_number: The just_number of this NumberOnly.  # noqa: E501
        :type just_number: float
        """
        self.swagger_types = {
            'just_number': float
        }

        self.attribute_map = {
            'just_number': 'JustNumber'
        }
        self._just_number = just_number

    @classmethod
    def from_dict(cls, dikt) -> 'NumberOnly':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NumberOnly of this NumberOnly.  # noqa: E501
        :rtype: NumberOnly
        """
        return util.deserialize_model(dikt, cls)

    @property
    def just_number(self) -> float:
        """Gets the just_number of this NumberOnly.


        :return: The just_number of this NumberOnly.
        :rtype: float
        """
        return self._just_number

    @just_number.setter
    def just_number(self, just_number: float):
        """Sets the just_number of this NumberOnly.


        :param just_number: The just_number of this NumberOnly.
        :type just_number: float
        """

        self._just_number = just_number
