# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SpecialModelName(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, special_property_name: int=None):  # noqa: E501
        """SpecialModelName - a model defined in Swagger

        :param special_property_name: The special_property_name of this SpecialModelName.  # noqa: E501
        :type special_property_name: int
        """
        self.swagger_types = {
            'special_property_name': int
        }

        self.attribute_map = {
            'special_property_name': '$special[property.name]'
        }
        self._special_property_name = special_property_name

    @classmethod
    def from_dict(cls, dikt) -> 'SpecialModelName':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The $special[model.name] of this SpecialModelName.  # noqa: E501
        :rtype: SpecialModelName
        """
        return util.deserialize_model(dikt, cls)

    @property
    def special_property_name(self) -> int:
        """Gets the special_property_name of this SpecialModelName.


        :return: The special_property_name of this SpecialModelName.
        :rtype: int
        """
        return self._special_property_name

    @special_property_name.setter
    def special_property_name(self, special_property_name: int):
        """Sets the special_property_name of this SpecialModelName.


        :param special_property_name: The special_property_name of this SpecialModelName.
        :type special_property_name: int
        """

        self._special_property_name = special_property_name
